version: '3.8'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    build: ./server
    volumes:
      - /app/node_modules/
      - ./server:/app
    environment:
      DB_HOST: db
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      GMAIL_LOGIN: ${GMAIL_LOGIN}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      PASSWORD_RESET_TTL: ${PASSWORD_RESET_TTL}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on: 
      - db

  admin:
    build: ./admin
    volumes:
      - /app/node_modules/
      - ./admin:/app
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      REACT_APP_SERVER_HOST: http://localhost:${BACKEND_PORT}
    ports:
      - "${ADMIN_PORT}:${ADMIN_PORT}"
    depends_on:
      - backend

  client:
    build: ./client
    volumes:
      - /app/node_modules/
      - ./client:/app
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      PORT: ${CLIENT_PORT}
      REACT_APP_SERVER_HOST: http://localhost:${BACKEND_PORT}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - backend

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog: 
    driver: local
